### ISSUE TITLE
Some underspecified link parsing corner cases

### ISSUE THREAD

**Issue by kivikakk** [commonmark/CommonMark#530] opened 2018-07-12 04:52 UTC
.@brson has unearthed a few areas where underspecification means that `cmark` and `comrak` had different link parsing behaviour despite both passing all specifications; see https://github.com/kivikakk/comrak/pull/80/files#diff-94ae0e030d77f337226703a7b6631921R852.

@jgm How do you feel about adding these to the spec in some form?

**Comment by jgm** [comment] 2018-07-12 17:58
As for `[a](\\ b)`, isn't this settled by the spec,
since URIs in links aren't allowed to contain spaces?

As for `[a](<<b)`, isn't this settled by the spec,
which says that a link destination may be "a sequence
of zero or more characters between an opening < and a
closing > that contains no line breaks or
unescaped < or > characters"?  (Here there's a
`<` character.)

As for `[a](<b\n)`, isn't this settled by the
"contains no line breaks" part?

So I don't see any of these as pointing to
underspecification, though maybe I'm missing
something.  The spec itself seems clear about
how these should be parsed.

There remains the question whether we should
put these test cases in the spec as examples.
I don't think that's clear, though I'm open
to persuasion.  The purpose of the examples is
to illustrate the rules, not to provide a completely
comprehensive set of tests, such that passing
the tests guarantees that the spec has been
correctly implemented. We could add many more
spec examples, and this would increase the
probability that an implementation passing
the spec test is correct, but at the cost of
decreasing the readability of the spec.

What's your take on this tradeoff in this
case?  Do you think we don't have enough examples
illustrating the rules of the `<...>` form of link
destination?

John

**Comment by jgm** [comment] 2018-07-12 20:29
Note that the `test/` directory has `regressions.txt`, which I've been
using for cases that should be tested but don't seem to belong in the
spec as examples.

**Comment by kivikakk** [comment] 2018-07-13 03:41
> Do you think we don't have enough examples illustrating the rules of the `<...>` form of link destination?

Perhaps we do, however I'm inclined to think these should perhaps be added to `regressions.txt` then. It's useful for implementors to have corner cases to test against that aren't executable examples in the spec itself; in this case, `comrak` was not compliant with these rules despite passing all spec examples.

**Comment by jgm** [comment] 2018-07-13 16:12
Definitely worth adding to regressions.txt.  Can you
prepare a PR?

**Comment by kivikakk** [comment] 2018-07-13 17:42
:+1: I’ll get on it on Monday!

**Closed** 2018-07-20 02:58 UTC
